### ISSUE TITLE
Stream Response not working

### ISSUE THREAD

**Issue by NereaCassian** [dotneet/smart-chatbot-ui#122]
The responses of the AI are not being streamed
![image](https://github.com/dotneet/smart-chatbot-ui/assets/70113068/b86f4987-036e-4413-9f81-8cfdcb69588c)

i have the ui deployed o a linux VPS with 11gigs and 8vcores

**Comment by nic-foma** [comment]
I noticed streaming stopped working for me, so went back and set everything up again. It all worked fine until I enabled HTTPS (using certbot for nginx). Once I was using HTTPS streaming stopped working.

**Comment by nic-foma** [comment]
This appears to be an issue when using nginx as a reverse proxy. Adding `proxy_buffering off;` in the location block fixed it.

**Comment by NereaCassian** [comment]
Yep doing that solved it.
