### ISSUE TITLE
Wikipedia plugin: Unsupported locale

### ISSUE THREAD

**Issue by drdada** [dotneet/smart-chatbot-ui#132]
Hello,
First, thank you a lot your amazing job ! This project is so cool.
I spotted a bug while using the wikipedia plugin.
I guess it's because it didn't support the french locale.

The errors logged is:
```
smart-chatbot-ui-chatui-1  | Error: Unsupported locale: fr-FR
smart-chatbot-ui-chatui-1  |     at Object.execute (/app/.next/server/chunks/542.js:521:19)
smart-chatbot-ui-chatui-1  |     at executeTool (/app/.next/server/chunks/317.js:52:21)
smart-chatbot-ui-chatui-1  |     at async handler (/app/.next/server/pages/api/runplugin.js:160:28)
```

**Comment by Sperrows** [comment]
<img width="357" alt="image" src="https://github.com/dotneet/smart-chatbot-ui/assets/108450670/361619f5-bcd2-4e53-b1a3-21b04bb06d53">
Got same error, but with en-US
