### ISSUE TITLE
Next Auth

### ISSUE THREAD

**Issue by QuickResolveAI** [dotneet/smart-chatbot-ui#39]
Hi,

Can you give me some guidance on how to integrate the next auth service to work with AWS Cognito?

**Comment by dotneet** [comment]
@QuickResolveAI 

Please try `feature/cognito-provider` branch.
https://github.com/dotneet/smart-chatbot-ui/pull/40

Please ensure that the following environment variables are set in the .env.local file before running.

COGNITO_CLIENT_ID=
COGNITO_CLIENT_SECRET=
COGNITO_ISSUER=

**Comment by QuickResolveAI** [comment]
Thank you for this 👍👌
